### PR TITLE
Cookbook docs

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Only two demos for now
 - dbmon
 - "kitchen sink" -- though this is a copy of the main demo for now, because this is waiting on [this PR](https://github.com/CrowdStrike/ember-headless-table/pull/4) before adding more stuff
 
 If anyone has other ideas for "how to do X", those would be a good candidate for these types of docs.
 
 Later, we'll probably want a whole separate page / nav for _most_ of these kinds of demos, as we may have a lot.
 
 Funnest demo: https://8dbbebed.ember-headless-table.pages.dev/docs/demos/lots-of-data
 
 
 After working with these demos a bit, I'm going to be spending some of my time working with Docfy to make the authoring experience a bit better:
  - actual js/ts/hbs/gjs/gts files
  - inline gjs demos (no demos folder)
  - probably other stuff

### CODE REVIEW

**Comment by nicolechung** [comment]
I am so shocked that https://8dbbebed.ember-headless-table.pages.dev/docs/demos/lots-of-data is not crashing my browser.

Some of the "edit links work", but some are broken:
Screen Shot 2022-10-12 at 7 58 20 PM
Screen Shot 2022-10-12 at 7 57 57 PM

**Review by nicolechung — APPROVED** [review]
Can confirm I ran locally and could use
- the main demos
- the plugin demos

**Comment by NullVoxPopuli** [comment]
> not crashing my browser.

requestAnimationFrame is a powerful tool :D 

> the "edit links work", but some are broken

yeah, they don't work on PRs

**Review by ynotdraw — APPROVED** [review]
Excellent!

**Pull request merged**
